# 24_np.yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: np-backend
  namespace: snake
spec:
  podSelector:
    matchLabels:
      app: backend
  policyTypes:
    - Egress                    # policy is only about Egress
  egress:
    -                            
      to:                           
      - podSelector:
          matchLabels:
            app: db1
      ports:                        
      - protocol: TCP
        port: 8080
    - 
      ports:
      - protocol: UDP
        port: 53
      - protocol: TCP
        port: 53
