# 24_np.yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: np-backend
  namespace: snake
spec:
  podSelector:
    matchLabels:
      app: backend
  policyTypes:
    - Egress                    # policy is only about Egress
  egress:
    -                           # first rule
      to:                           # first condition "to"
      - podSelector:
          matchLabels:
            app: db1
      ports:                        # second condition "port"
      - protocol: TCP
        port: 1111
    -                           # first rule
      to:                           # first condition "to"
      - podSelector:
          matchLabels:
            app: db1
      ports:                        # second condition "port"
      - protocol: TCP
        port: 8080
    -                           # first rule
      to:                           # first condition "to"
      - podSelector:
          matchLabels:
            app: db111
      ports:                        # second condition "port"
      - protocol: TCP
        port: 1111
    -                           # first rule
      to:                           # first condition "to"
      - podSelector:
          matchLabels:
            app: db81
      ports:                        # second condition "port"
      - protocol: TCP
        port: 1111
      - protocol: TCP
        port: 81
    -                           # second rule
      to:                           # first condition "to"
      - podSelector:
          matchLabels:
            app: db2
      ports:                        # second condition "port"
      - protocol: TCP
        port: 2222
      - protocol: TCP
        port: 443
    - 
      ports:
      - protocol: UDP
        port: 53
      - protocol: TCP
        port: 53
