apiVersion: v1
kind: Service
metadata:
  labels:
    app: db1
  name: db1
  namespace: snake
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: db1
status:
  loadBalancer: {}
